### ISSUE TITLE
Search "button" is a link

### ISSUE THREAD

**Issue by catalinpit** [catalinpit/attila-theme#3]
The search "button" is a link, and Lighthouse marks it as an error. I believe this should be a button, unless I'm wrong.

![search](https://github.com/catalinpit/attila-theme/assets/25515812/4a79ed62-3a45-4aef-8a8b-4646742cb333)

**Comment by Em3c2** [comment]
Hi Catalin! Can you please assign me this issue?

**Comment by catalinpit** [comment]
> Hi Catalin! Can you please assign me this issue?

Done! Thanks 🙌

**Comment by Em3c2** [comment]
Done! I hope it's okay 🦾

**Comment by catalinpit** [comment]
Fixed by https://github.com/catalinpit/attila-theme/pull/5. Thanks a lot once again @emiliacb! Appreciate the help! 🙏
