### ISSUE TITLE
YouTube embeds are too small

### ISSUE THREAD

**Issue by catalinpit** [catalinpit/attila-theme#4]
The YouTube embeds are too small. They should be bigger.

![asf](https://github.com/catalinpit/attila-theme/assets/25515812/8f437ae7-a0ff-4387-ab99-ee6dc097299d)

**Comment by 0-vortex** [comment]
Looks like you have a jQuery extension to do this already in [/src/js/libs/jquery.fitvids.js](https://github.com/catalinpit/attila-theme/blob/main/src/js/libs/jquery.fitvids.js) but it is not called like `post.fitVids()` in `post.hbs`: https://github.com/catalinpit/attila-theme/blob/c0b17c1ddd79d1f88caefc349de40dde7a4994be/post.hbs#L197

**Comment by catalinpit** [comment]
> Looks like you have a jQuery extension to do this already in [/src/js/libs/jquery.fitvids.js](https://github.com/catalinpit/attila-theme/blob/main/src/js/libs/jquery.fitvids.js) but it is not called like `post.fitVids()` in `post.hbs`:
> 
> https://github.com/catalinpit/attila-theme/blob/c0b17c1ddd79d1f88caefc349de40dde7a4994be/post.hbs#L197

Thanks for the comment! If you want and can fix it, feel free to go ahead. :-)

**Comment by catalinpit** [comment]
Fixed by https://github.com/catalinpit/attila-theme/pull/6. Thanks a lot for the PR! Highly appreciate it!
